### PR TITLE
Let authconfig do the heavy lifting, add Amazon Linux support...

### PR DESCRIPTION
**Pull request by jorhett**
This pull request ensures that authconfig is installed (not in minimal installs) and installs all the ldap packages before running authconfig, such that authconfig will modify their configurations properly.

It's flexible for supporting both SSSD and non-SSSD configurations for CentOS 6, and handles CentOS 7 as well.

If you like this, I'll do some work to clean up the README and other stuff too.

### CODE REVIEW

**Comment by jcam** [comment]
Apologies for not noticing your PR until now. Is this still ready for merge?

**Comment by jorhett** [comment]
AFAIK we used it extensively when I was there. I've left, but you can compare against CheggEng/authconfig for what we ended up with that supported CentOS 5, 6, and 7 properly.

**Comment by Sauraus** [comment]
So where did we leave this?

**Comment by jcam** [comment]
I think this is ready to be merged and tested... I think it might warrant a 2.0 release, since it changes centos 5 functionality (installs and enables SSSD for cent5, if i am reading it correctly), and adds support for cent 7.

**Comment by Sauraus** [comment]
CentOS 5 is EOL, not sure how much value there is in keeping that around.

I am about to merge all these changes into a branch and test on CentOS 6.7 and 7.x

**Comment by jcam** [comment]
Are you taking the CheggEng changes as well?

**Comment by Sauraus** [comment]
I merged their entire 'master' branch eg. what is in this pull request into a branch and I am trying to get it running now.

**Comment by jcam** [comment]
@Sauraus how is this looking?

**Comment by Sauraus** [comment]
Well the merge is clean.. however testing is not straight forward, working on that now.

**Comment by jcam** [comment]
Okay, let me know if I can help out with the testing at all... I have not much time usually for this project, but could try running it on one of the test environments at work

**Comment by Sauraus** [comment]
I was able to get this all working :) but had to add 'AD' as a provider because of my infrastructure requiring it. https://github.com/jcam/authconfig/pull/41

**Comment by jcam** [comment]
@jorhett I ended up not merging this one, and taking #41 instead. Please feel free to put in a PR against that if something from this was missed, though I believe that @Sauraus managed to incorporate your changes.

**Pull request merged**
